{
 "title": "Vault",
 "description": "Vault Metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace:",
    "query": "label_values(vault_route, namespace)"
   },
   {
    "name": "deployment",
    "query": "label_values(kube_pod_info{namespace='$namespace',pod=~'vault-.*'}, pod)"
   },
   {
    "name": "path",
    "label": "Path:",
    "query": "label_values(vault_route_count, path)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "query": "metrics(vault_metrics_collection_)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(increase(vault_audit_log_response_count{namespace=\"vault\",pod=\"vault-0\"}[1m]) or up{namespace=\"vault\",pod=\"vault-0\"}) by (pod)",
     "legendFormat": "vault-0"
    },
    {
     "expr": "max(increase(vault_audit_log_response_count{namespace=\"vault\",pod=\"vault-1\"}[1m]) or up{namespace=\"vault\",pod=\"vault-1\"}) by (pod)",
     "legendFormat": "vault-1"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1+(vault_vault_0_core_unsealed_vault_cluster_${cluster}{} or vault_vault_1_core_unsealed_vault_cluster_${cluster}{}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "repeat": "node",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(vault_vault_0_secret_kv_count_root_secret__vault_cluster_${cluster}) or max(vault_vault_1_secret_kv_count_root_secret__vault_cluster_${cluster})"
    }
   ]
  },
  {
   "title": "Identity Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_vault_0_identity_num_entities) or max(vault_vault_1_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_vault_0_expire_num_leases) or max(vault_vault_1_expire_num_leases)"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log Request Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_request_failure[$interval]))",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Log Requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 20, "x": 4, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Requests per second" }
     ],
     "targets": [
      {
       "expr": "sum(irate(vault_audit_log_request_count[$interval]))",
       "legendFormat": "Request "
      },
      {
       "expr": "sum(irate(vault_audit_log_response_count[$interval]))",
       "legendFormat": "Response"
      },
      {
       "expr": "sum(irate(vault_core_handle_request_count[$interval]))",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Log Response Failures",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_response_failure[$interval]))",
       "legendFormat": "Request"
      }
     ]
    }
   ]
  },
  {
   "title": "DynamoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "DynamoDB Get Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max(increase(vault_dynamodb_get_count{namespace=\"$namespace\"}[$interval])) by (pod)) by (namespace, pod)",
       "legendFormat": "{{pod}}/get"
      }
     ]
    },
    {
     "title": "DynamoDB List Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max(increase(vault_dynamodb_list_count{namespace=\"$namespace\"}[$interval])) by (pod)) by (namespace, pod)",
       "legendFormat": "{{pod}}/list"
      }
     ]
    },
    {
     "title": "DynamoDB Put Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max(increase(vault_dynamodb_put_count{namespace=\"$namespace\"}[$interval])) by (pod)) by (namespace, pod)",
       "legendFormat": "{{pod}}/put"
      }
     ]
    },
    {
     "title": "DynamoDB Delete Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(max(increase(vault_dynamodb_delete_count{namespace=\"$namespace\"}[$interval])) by (pod)) by (namespace, pod)",
       "legendFormat": "{{pod}}/delete"
      }
     ]
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy Set",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(vault_policy_set_policy_count[1m]))",
       "legendFormat": "SET"
      }
     ]
    },
    {
     "title": "Policy Get",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(irate(vault_policy_get_policy_count[1m]))",
       "legendFormat": "GET"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Info: $path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "path",
   "collapsed": true,
   "panels": [
    {
     "title": "`$path` operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Operations" }
     ],
     "targets": [
      {
       "expr": "sum(increase(vault_route_count{path=\"$path\"}[$interval])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "`$path` operation elapsed time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms", "label": "Time of one operation" }
     ],
     "targets": [
      {
       "expr": "sum(increase(vault_route_sum{path=\"$path\"}[$interval])/increase(vault_route_count{path=\"$path\"}[$interval])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Resource Stats ($deployment)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "deployment",
   "collapsed": true,
   "panels": [
    {
     "title": "Running pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'$deployment'})"
      },
      {
       "expr": "sum(kube_statefulset_status_replicas_ready{namespace='$namespace',statefulset=~'$deployment'})"
      }
     ]
    },
    {
     "title": "Unavailable pods",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'$deployment'})"
      }
     ]
    },
    {
     "title": "Pods distributed on hosts",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(count(container_memory_working_set_bytes{namespace='$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (node))"
      }
     ]
    },
    {
     "title": "Max pods restarts (last 5 minutes)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}[5m]))) by (pod)"
      }
     ]
    },
    {
     "title": "Pod count (total, avail, unvail) and pods hosts distribution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace='$namespace',deployment=~'$deployment'} or kube_statefulset_status_replicas{namespace='$namespace',statefulset=~'$deployment'}",
       "legendFormat": "Total Pods"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace='$namespace',deployment=~'$deployment'} or kube_statefulset_status_replicas_ready{namespace='$namespace',statefulset=~'$deployment'}",
       "legendFormat": "Pods Ready or Available"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{namespace='$namespace',deployment=~'$deployment'} or (kube_statefulset_status_replicas{namespace='$namespace',statefulset=~'$deployment'} -kube_statefulset_status_replicas_ready{namespace='$namespace',statefulset=~'$deployment'})",
       "legendFormat": "Pods Unavailable or Not Ready"
      },
      {
       "expr": "count(count(container_memory_working_set_bytes{namespace='$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (node))",
       "legendFormat": "Hosts with Pods"
      }
     ]
    },
    {
     "title": "Pods restarts (last 5 minutes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace='$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}[5m])) by (pod)",
       "legendFormat": "{{ '{{' }}pod{{ '}}' }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {}
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$', container!=''}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$', container!=''}) by (pod)",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)",
       "legendFormat": "Memory Requests"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)",
       "legendFormat": "Memory Requests %"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)",
       "legendFormat": "Memory Limits"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}) by (pod)",
       "legendFormat": "Memory Limits %"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace',pod=~'$deployment-([0-9]+|[a-z0-9]+-[a-z0-9]+)$'}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}